
#####################
### LOOK AND FEEL ###
#####################

# Refer to https://wiki.hypr.land/Configuring/Variables/

# https://wiki.hypr.land/Configuring/Variables/#general
general {
    gaps_in = 5
    gaps_out = 10

    border_size = 2

    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(973737ff)
    col.inactive_border = rgba(777777cc)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false

    # Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = false 

    layout = dwindle
}

# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
    rounding = 0
    rounding_power = 2

    # Change transparency of focused and unfocused windows
    active_opacity = 0.98
    inactive_opacity = 0.89

    shadow {
        enabled = false
        range = 10
        render_power = 3 
        color = rgba(1a3a3aff)
    }

    # https://wiki.hypr.land/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 8
        passes = 3
	new_optimizations = true
        ignore_opacity = true

	noise = 0.02
	contrast = 1.2
	vibrancy = 0.1696
    }
	blurls = rofi
}

