general {
    hide_cursor = false
}

background {
	monitor = 
	path = $HOME/.config/wallPapr/blur_w1.png
}

# input field
input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    rounding = 1
    dots_size = 0.3 # scaled by input-field height
    dots_spacing = 0.15 # scaled by input-field height
    dots_center = true
    fade_on_empty = false 
    outer_color = rgb(e6e6e6)
    inner_color = rgb(292929)
    font_color = rgb(e6e6e6)
    placeholder_text = <span foreground="##d9d9d9"><i>input_passwd</i></span>
    check_color = rgb(204, 136, 34)
    fail_color = rgb(204, 34, 34)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_timeout = 1000
    capslock_color = -1
    font_family = Fira Code Semibold
    halign = center
    valign = center
    position = 0, -70
}

# authenticate
auth {
    # at least one enabled authentication method is required
    # password is the default and should be enabled unless you use a different method
    password {
        enabled = true
    }
}

# clock
label {
    monitor =
    text = cmd[update:1000] date +"%-I:%M%p"
    color = rgb(e6e6e6)
    font_size = 15
    font_family = Fira Code Semibold
    position = 580, 270
    halign = center
    valign = center
    #shadow_passes = 2
    #shadow_sizes = 2	
}

label {
	monitor = 
	text = cmd[update:1000] date +"%B %d, %Y"
	color = rgb(e6e6e6)

	font_family = Fira Code Semibold
	font_size = 15
	position = -520, 270
	halign = center
	valign = center
}

image {
	monitor = 
	path = $HOME/.config/wallPapr/avatar_s.png
	size = 200
	rounding = 0
	border_size = 0

	position = 0, 57
	halign = center
	valign = center
	#shadow_passes = 3
	#shadow_sizes = 8
}

